import { Router } from 'express'; import { Scheme, Patient, SchemeEnrollment } from '../models/index.js'; import { auth } from '../middleware/auth.js'; import { awardOnce } from '../services/rewards.js';
const router=Router(); router.use(auth);
function matches(s,p){const r=s.eligibilityRules||{};return(!r.gender||r.gender===p.gender)&&(!r.categories?.length||r.categories.some(c=>p.healthCategories.includes(c)))}
router.get('/',async(req,res)=>res.json({success:true,message:'Schemes loaded',data:{schemes:await Scheme.find().sort({schemeName:1})}}));
router.get('/recommended/:patientId',async(req,res)=>{const p=await Patient.findById(req.params.patientId);if(!p)return res.status(404).json({success:false,message:'Patient not found'});const schemes=(await Scheme.find()).filter(s=>matches(s,p));const enrollments=await SchemeEnrollment.find({patientId:p._id});res.json({success:true,message:'Recommendations loaded',data:{schemes:schemes.map(s=>({...s.toObject(),whyEligible:`Patient profile includes ${p.healthCategories.join(', ')}. Confirm final eligibility on the official source.`,enrollment:enrollments.find(e=>String(e.schemeId)===String(s._id))||null}))}})});
router.post('/:schemeId/enroll',async(req,res,next)=>{try{let enrollment=await SchemeEnrollment.findOne({patientId:req.body.patientId,schemeId:req.params.schemeId});if(!enrollment)enrollment=await SchemeEnrollment.create({patientId:req.body.patientId,schemeId:req.params.schemeId,workerId:req.user._id});res.status(201).json({success:true,message:'Registration started',data:{enrollment}})}catch(e){next(e)}});
router.patch('/enrollments/:id',async(req,res,next)=>{try{const e=await SchemeEnrollment.findById(req.params.id);if(!e)return res.status(404).json({success:false,message:'Enrollment not found'});if(req.body.status==='registered'){e.status='registered';e.registeredAt=e.registeredAt||new Date()}await e.save();let awarded=false;if(e.status==='registered'){({awarded}=await awardOnce({workerId:req.user._id,patientId:e.patientId,actionType:'scheme_registered',relatedId:e._id,description:'Scheme registration verified'}))}res.json({success:true,message:awarded?'Registration confirmed. 10 points awarded.':'Status saved; no duplicate points awarded.',data:{enrollment:e,awarded}})}catch(err){next(err)}});
export default router;

