import{useEffect,useState}from'react';import{AlertCircle,ChevronLeft}from'lucide-react';import{useNavigate}from'react-router-dom';
export function Logo({size=48,withText=true}){return <div className="flex items-center gap-3"><img src="/icon.svg" className="rounded-2xl shadow-lg" style={{width:size,height:size}} alt="AshaCare logo"/>{withText&&<span className="text-2xl font-black tracking-tight text-care-700">Asha<span className="text-care-400">Care</span></span>}</div>}
export function PageHeader({title,back=false,action}){const nav=useNavigate();return <header className="sticky top-0 z-20 flex items-center justify-between bg-[#f4faf7]/90 px-5 py-4 backdrop-blur-xl"><div className="flex items-center gap-3">{back&&<button onClick={()=>nav(-1)} className="grid h-10 w-10 place-items-center rounded-2xl bg-white" aria-label="Go back"><ChevronLeft/></button>}<h1 className="text-xl font-black text-care-ink">{title}</h1></div>{action}</header>}
export function Loading(){return <div className="grid min-h-[50vh] place-items-center"><div className="h-9 w-9 animate-spin rounded-full border-4 border-care-100 border-t-care-600"/></div>}
export function ErrorState({message,onRetry}){return <div className="card m-5 p-6 text-center"><AlertCircle className="mx-auto mb-3 text-amber-500"/><p className="text-sm text-slate-600">{message}</p>{onRetry&&<button className="btn-secondary mt-4" onClick={onRetry}>Try again</button>}</div>}
export function useLoad(loader,deps=[]){const[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const load=()=>{setLoading(true);setError('');loader().then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,deps);return{data,error,loading,reload:load,setData}}
export function Toast({message,onDone}){useEffect(()=>{const id=setTimeout(onDone,2800);return()=>clearTimeout(id)},[message]);return message?<div className="fixed bottom-24 left-1/2 z-50 w-[min(390px,calc(100%-32px))] -translate-x-1/2 rounded-2xl bg-care-ink px-4 py-3 text-center text-sm font-semibold text-white shadow-xl">{message}</div>:null}
export function RiskBadge({risk,t}){const style={red:'bg-red-50 text-red-700 border-red-100',yellow:'bg-amber-50 text-amber-700 border-amber-100',green:'bg-emerald-50 text-emerald-700 border-emerald-100'}[risk];return <span className={`rounded-full border px-2.5 py-1 text-[11px] font-black uppercase ${style}`}>{t?t(risk):risk}</span>}

