import assert from 'node:assert/strict';
const base='http://localhost:5000/api';let token;
async function req(path,{method='GET',body,form=false}={}){const r=await fetch(base+path,{method,headers:{...(token?{Authorization:`Bearer ${token}`} :{}),...(!form&&body?{'Content-Type':'application/json'}:{})},body:body?(form?body:JSON.stringify(body)):undefined});const j=await r.json();if(!r.ok)throw new Error(`${path}: ${j.message}`);return j.data}
const signupMarker=Date.now();const signup=await req('/auth/signup',{method:'POST',body:{fullName:'QA Signup Worker',phoneNumber:`8${String(signupMarker).slice(-9)}`,email:`qa-${signupMarker}@demo.in`,password:'Test@1234',preferredLanguage:'mr'}});assert.equal(signup.currentUser.role,'asha_worker');assert.equal(signup.currentUser.preferredLanguage,'mr');
const auth=await req('/auth/login',{method:'POST',body:{email:'asha@demo.in',password:'Demo@123'}});token=auth.authToken;assert.equal(auth.currentUser.role,'asha_worker');
const dashboard=await req('/dashboard');assert.ok(dashboard.stats);assert.ok(dashboard.calendar);
const searched=await req('/patients?search=Sunita');assert.equal(searched.patients.length,1);
const marker=Date.now();const created=await req('/patients',{method:'POST',body:{fullName:`QA Patient ${marker}`,age:34,gender:'female',phoneNumber:`91${String(marker).slice(-8)}`,address:'QA address',village:'QA village',healthCategories:['pregnancy']}});const persisted=await req(`/patients/${created.patient._id}`);assert.equal(persisted.patient.fullName,`QA Patient ${marker}`);
const screened=await req('/cases',{method:'POST',body:{patientId:created.patient._id,screening:{temperature:39.5,dangerSigns:['bleeding'],symptoms:['fever']}}});assert.equal(screened.careCase.riskLevel,'red');assert.equal(screened.careCase.doctorVisitWithinDays,1);
const schemes=await req(`/schemes/recommended/${created.patient._id}`);assert.ok(schemes.schemes.length>=2);const started=await req(`/schemes/${schemes.schemes[0]._id}/enroll`,{method:'POST',body:{patientId:created.patient._id}});const confirmed=await req(`/schemes/enrollments/${started.enrollment._id}`,{method:'PATCH',body:{status:'registered'}});assert.equal(confirmed.awarded,true);const duplicate=await req(`/schemes/enrollments/${started.enrollment._id}`,{method:'PATCH',body:{status:'registered'}});assert.equal(duplicate.awarded,false);
const form=new FormData();form.append('doctorVisited','true');form.append('notes','QA verified');form.append('proof',new Blob(['valid proof'],{type:'application/pdf'}),'proof.pdf');const proof=await req(`/cases/${screened.careCase._id}/proof`,{method:'POST',body:form,form:true});assert.equal(proof.awarded,true);const form2=new FormData();form2.append('doctorVisited','true');form2.append('proof',new Blob(['valid proof duplicate'],{type:'application/pdf'}),'proof2.pdf');const proofAgain=await req(`/cases/${screened.careCase._id}/proof`,{method:'POST',body:form2,form:true});assert.equal(proofAgain.awarded,false);
const notifications=await req('/notifications');if(notifications.notifications[0])await req(`/notifications/${notifications.notifications[0]._id}/read`,{method:'PATCH'});
const profile=await req('/auth/me',{method:'PATCH',body:{preferredLanguage:'hi'}});assert.equal(profile.currentUser.preferredLanguage,'hi');await req('/auth/me',{method:'PATCH',body:{preferredLanguage:'en'}});
const rewards=await req('/rewards');assert.ok(rewards.totalPoints>=40);assert.ok(rewards.rank>=1);const supervisor=await req('/auth/login',{method:'POST',body:{email:'supervisor@demo.in',password:'Demo@123'}});token=supervisor.authToken;const overview=await req('/dashboard/supervisor');assert.ok(overview.workers>=2);assert.ok(overview.patients>=12);console.log(JSON.stringify({ok:true,patientId:created.patient._id,caseId:screened.careCase._id,totalPoints:rewards.totalPoints,checks:22,supervisorOverview:true},null,2));
