import assert from 'node:assert/strict';
const base=process.env.API_BASE||'http://localhost:5000/api';let token;
async function req(path,{method='GET',body,form=false}={}){const r=await fetch(base+path,{method,headers:{...(token?{Authorization:`Bearer ${token}`} :{}),...(!form&&body?{'Content-Type':'application/json'}:{})},body:body?(form?body:JSON.stringify(body)):undefined});const j=await r.json();if(!r.ok)throw new Error(`${path}: ${j.message}`);return j.data}
const futureDate=days=>{const date=new Date();date.setDate(date.getDate()+days);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`};
const signupMarker=Date.now();const signup=await req('/auth/signup',{method:'POST',body:{fullName:'QA Signup Worker',ashaId:`ASHA-QA-${signupMarker}`,phoneNumber:`8${String(signupMarker).slice(-9)}`,email:`qa-${signupMarker}@demo.in`,password:'Test@1234',preferredLanguage:'mr'}});assert.equal(signup.currentUser.role,'asha_worker');assert.equal(signup.currentUser.preferredLanguage,'mr');
const otpRequest=await req('/auth/request-otp',{method:'POST',body:{ashaId:'ASHA-ANAND-001'}});assert.equal(otpRequest.maskedPhone.endsWith('0001'),true);assert.equal(otpRequest.maskedPhone.includes('900000'),false);const auth=await req('/auth/verify-otp',{method:'POST',body:{ashaId:'ASHA-ANAND-001',otp:otpRequest.demoOtp}});token=auth.authToken;assert.equal(auth.currentUser.role,'asha_worker');
const photoProfile=await req('/auth/me',{method:'PATCH',body:{profilePhoto:'data:image/png;base64,AA=='}});assert.equal(photoProfile.currentUser.profilePhoto,'data:image/png;base64,AA==');const clearedPhoto=await req('/auth/me',{method:'PATCH',body:{profilePhoto:''}});assert.equal(clearedPhoto.currentUser.profilePhoto,'');
const locatedProfile=await req('/auth/me',{method:'PATCH',body:{assignedRegion:'QA GPS Locality, Gujarat, India'}});assert.equal(locatedProfile.currentUser.assignedRegion,'QA GPS Locality, Gujarat, India');await req('/auth/me',{method:'PATCH',body:{assignedRegion:'Anand Rural'}});
const dashboard=await req('/dashboard');assert.ok(dashboard.stats);assert.ok(dashboard.calendar);
const searched=await req('/patients?search=Sunita');assert.equal(searched.patients.length,1);
const marker=Date.now();const followUpDate=futureDate(14);const created=await req('/patients',{method:'POST',body:{fullName:`QA Beneficiary ${marker}`,age:34,gender:'female',phoneNumber:`91${String(marker).slice(-8)}`,address:'QA address',village:'QA village',healthCategories:['pregnancy'],currentRiskLevel:'yellow',nextFollowUpDate:followUpDate,description:'QA optional context',piiConsent:true}});const persisted=await req(`/patients/${created.patient._id}`);assert.equal(persisted.patient.fullName,`QA Beneficiary ${marker}`);assert.equal(persisted.patient.piiConsent,true);assert.equal(persisted.patient.currentRiskLevel,'yellow');assert.equal(persisted.patient.description,'QA optional context');assert.equal(persisted.patient.nextFollowUpDate.slice(0,10),followUpDate);
const tooLateForHighRisk=futureDate(8);await assert.rejects(()=>req('/patients',{method:'POST',body:{fullName:'QA Invalid Follow-up',age:30,gender:'female',village:'QA village',healthCategories:['general'],currentRiskLevel:'red',nextFollowUpDate:tooLateForHighRisk,piiConsent:true}}),/Follow-up for red risk/);
const screened=await req('/cases',{method:'POST',body:{patientId:created.patient._id,screening:{temperature:39.5,dangerSigns:['bleeding'],symptoms:['fever']}}});assert.equal(screened.careCase.riskLevel,'red');assert.equal(screened.careCase.doctorVisitWithinDays,1);
const schemes=await req(`/schemes/recommended/${created.patient._id}`);assert.ok(schemes.schemes.length>=2);assert.equal(schemes.location.state,'Gujarat');assert.ok(schemes.schemes.some(scheme=>scheme.governmentLevel==='central'));assert.ok(schemes.schemes.some(scheme=>scheme.governmentLevel==='state'));assert.equal(schemes.schemes.some(scheme=>scheme.schemeName==='Nikshay Poshan Yojana'),false);const tbBeneficiary=(await req('/patients?search=Vijay')).patients[0];const tbSchemes=await req(`/schemes/recommended/${tbBeneficiary._id}`);assert.ok(tbSchemes.schemes.some(scheme=>scheme.schemeName==='Nikshay Poshan Yojana'));await req('/auth/me',{method:'PATCH',body:{assignedRegion:'Pune, Maharashtra, India'}});const maharashtraSchemes=await req(`/schemes/recommended/${created.patient._id}`);assert.equal(maharashtraSchemes.location.state,'Maharashtra');assert.equal(maharashtraSchemes.schemes.some(scheme=>scheme.governmentLevel==='state'),false);await req('/auth/me',{method:'PATCH',body:{assignedRegion:'Anand Rural'}});const started=await req(`/schemes/${schemes.schemes[0]._id}/enroll`,{method:'POST',body:{patientId:created.patient._id}});const confirmed=await req(`/schemes/enrollments/${started.enrollment._id}`,{method:'PATCH',body:{status:'registered'}});assert.equal(confirmed.awarded,true);const duplicate=await req(`/schemes/enrollments/${started.enrollment._id}`,{method:'PATCH',body:{status:'registered'}});assert.equal(duplicate.awarded,false);
const form=new FormData();form.append('doctorVisited','true');form.append('notes','QA verified');form.append('proof',new Blob(['valid proof'],{type:'application/pdf'}),'proof.pdf');const proof=await req(`/cases/${screened.careCase._id}/proof`,{method:'POST',body:form,form:true});assert.equal(proof.awarded,true);const form2=new FormData();form2.append('doctorVisited','true');form2.append('proof',new Blob(['valid proof duplicate'],{type:'application/pdf'}),'proof2.pdf');const proofAgain=await req(`/cases/${screened.careCase._id}/proof`,{method:'POST',body:form2,form:true});assert.equal(proofAgain.awarded,false);
const notifications=await req('/notifications');if(notifications.notifications[0])await req(`/notifications/${notifications.notifications[0]._id}/read`,{method:'PATCH'});
const profile=await req('/auth/me',{method:'PATCH',body:{preferredLanguage:'hi'}});assert.equal(profile.currentUser.preferredLanguage,'hi');await req('/auth/me',{method:'PATCH',body:{preferredLanguage:'en'}});
const rewards=await req('/rewards');assert.ok(rewards.totalPoints>=40);assert.ok(rewards.rank>=1);const allRewards=await req('/rewards?all=true');assert.ok(allRewards.transactions.length>=rewards.transactions.length);const deleted=await req(`/patients/${created.patient._id}`,{method:'DELETE'});assert.equal(deleted.deleted,true);const supervisorOtp=await req('/auth/request-otp',{method:'POST',body:{ashaId:'SUP-KHEDA-001'}});const supervisor=await req('/auth/verify-otp',{method:'POST',body:{ashaId:'SUP-KHEDA-001',otp:supervisorOtp.demoOtp}});token=supervisor.authToken;const overview=await req('/dashboard/supervisor');assert.ok(overview.workers>=2);assert.ok(overview.patients>=12);console.log(JSON.stringify({ok:true,deletedBeneficiaryId:created.patient._id,totalPoints:rewards.totalPoints,checks:43,supervisorOverview:true},null,2));
