import { useState } from "react";
import { Link } from "react-router-dom";
import { useLanguage } from "../i18n";
const AddBeneficiaryPage = () => {
 const { t, preferredLanguage } = useLanguage(); const [fullName, setFullName] = useState(""); const [age, setAge] = useState(""); const [sex, setSex] = useState(""); const [phoneNumber, setPhoneNumber] = useState(""); const [village, setVillage] = useState(""); const [success, setSuccess] = useState(false);
 const saveBeneficiary = (event) => { event.preventDefault(); const patients = JSON.parse(localStorage.getItem("mockPatients") || "[]"); patients.push({ _id: "local-patient-" + Date.now(), fullName, age: Number(age), sex, gender: sex, phoneNumber, village, preferredLanguage, healthCategories: [] }); localStorage.setItem("mockPatients", JSON.stringify(patients)); setSuccess(true); };
 if (success) return <div className="mx-auto max-w-xl px-4 py-10"><section className="rounded-2xl border border-emerald-200 bg-white p-6 text-center shadow-sm"><h1 className="text-2xl font-bold text-slate-900">{t.beneficiaryAdded}</h1><Link to="/patients" className="mt-6 inline-block rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">{t.backToPatients}</Link></section></div>;
 return <div className="mx-auto max-w-xl px-4 py-6 sm:px-6"><Link to="/patients" className="font-semibold text-emerald-800 underline">← {t.backToPatients}</Link><h1 className="mt-5 text-3xl font-bold text-slate-900">{t.addBeneficiary}</h1><form onSubmit={saveBeneficiary} className="mt-6 space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="block font-semibold text-slate-700">{t.patientName}<input required value={fullName} onChange={(e) => setFullName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3" /></label><label className="block font-semibold text-slate-700">{t.age}<input required min="0" type="number" value={age} onChange={(e) => setAge(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3" /></label><label className="block font-semibold text-slate-700">{t.sex}<select required value={sex} onChange={(e) => setSex(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3"><option value="">{t.select}</option><option value="female">{t.female}</option><option value="male">{t.male}</option><option value="other">{t.other}</option></select></label><label className="block font-semibold text-slate-700">{t.phoneNumber}<input inputMode="tel" value={phoneNumber} onChange={(e) => setPhoneNumber(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3" /></label><label className="block font-semibold text-slate-700">{t.villageWard}<input required value={village} onChange={(e) => setVillage(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3" /></label><p className="text-sm text-slate-600">{t.language}: {preferredLanguage === "hi" ? "हिंदी" : "English"}</p><button className="w-full rounded-xl bg-emerald-700 px-5 py-3.5 text-lg font-bold text-white">{t.saveBeneficiary}</button></form></div>;
}; export default AddBeneficiaryPage;
