import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { mockFollowUps } from "../mockData/followUps";
import { useLanguage } from "../i18n";
const FollowUpDetailPage = () => {
 const { followUpId } = useParams(); const { t } = useLanguage(); const followUp = mockFollowUps.find((item) => item._id === followUpId); const [proofFile, setProofFile] = useState(null); const [referenceNumber, setReferenceNumber] = useState(""); const [notes, setNotes] = useState(""); const [isSubmitting, setIsSubmitting] = useState(false); const [submitSuccess, setSubmitSuccess] = useState(false); const [errorMessage, setErrorMessage] = useState("");
 if (!followUp) return <div className="mx-auto max-w-xl px-4 py-10"><h1 className="text-2xl font-bold">{t.followUpNotFound}</h1><Link to="/follow-ups" className="mt-5 inline-block text-emerald-700 underline">{t.followUps}</Link></div>;
 const submit = (event) => { event.preventDefault(); if (!proofFile && !referenceNumber.trim()) { setErrorMessage(t.proofRequired); return; } setIsSubmitting(true); const submissions = JSON.parse(localStorage.getItem("mockFollowUpSubmissions") || "[]"); localStorage.setItem("mockFollowUpSubmissions", JSON.stringify([...submissions.filter((item) => item.followUpId !== followUpId), { followUpId, referenceNumber, notes, proofFileName: proofFile?.name, submittedAt: new Date().toISOString() }])); setIsSubmitting(false); setSubmitSuccess(true); };
 if (submitSuccess) return <div className="mx-auto max-w-xl px-4 py-10"><section className="rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold text-slate-900">{t.followUpSubmitted}</h1><Link to="/follow-ups" className="mt-6 inline-block rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">{t.backToFollowUps}</Link></section></div>;
 return <div className="mx-auto max-w-3xl px-4 py-6 sm:px-6"><Link to="/follow-ups" className="font-semibold text-emerald-800 underline">← {t.backToFollowUps}</Link><header className="mt-5"><h1 className="text-3xl font-bold text-slate-900">{followUp.patientName}</h1><p className="mt-1 text-slate-600">{followUp.village} · {followUp.condition}</p></header><section className="mt-6 grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2">{[[t.age, followUp.age], [t.healthCategory, followUp.condition], [t.visitType, followUp.visitType], [t.hospital, followUp.hospitalName], [t.visitDate, followUp.visitDate], [t.dueDate, followUp.dueDate], [t.currentStatus, followUp.status]].map(([label, value]) => <div key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-1 font-semibold capitalize text-slate-900">{value}</p></div>)}</section><form onSubmit={submit} className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-900">{t.proofUpload}</h2><p className="mt-1 text-slate-600">{t.proofHelp}</p>{errorMessage && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{errorMessage}</p>}<label className="mt-5 block font-semibold text-slate-700">{t.uploadProof}<input type="file" accept=".pdf,image/*" onChange={(event) => setProofFile(event.target.files?.[0] || null)} className="mt-2 block w-full text-sm" /></label><label className="mt-5 block font-semibold text-slate-700">{t.referenceNumber}<input value={referenceNumber} onChange={(event) => setReferenceNumber(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3" /></label><label className="mt-5 block font-semibold text-slate-700">{t.visitNotes}<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows="4" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3" /></label><button disabled={isSubmitting} className="mt-6 w-full rounded-xl bg-emerald-700 px-5 py-3.5 text-lg font-bold text-white disabled:opacity-60">{isSubmitting ? t.submitting : t.submitFollowUp}</button></form></div>;
}; export default FollowUpDetailPage;
