import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { mockFollowUps } from "../mockData/followUps";
import { useLanguage } from "../i18n";
const isDueThisWeek = (dueDate) => { const today = new Date("2026-08-21"); const due = new Date(dueDate); return due >= today && due <= new Date(today.getTime() + 7 * 86400000); };
const FollowUpsPage = () => {
 const { t } = useLanguage(); const [followUps, setFollowUps] = useState([]); const [followUpFilter, setFollowUpFilter] = useState("all"); const [isLoading, setIsLoading] = useState(true); const [errorMessage] = useState("");
 useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("mockFollowUpSubmissions") || "[]"); setFollowUps(mockFollowUps.map((item) => saved.find((entry) => entry.followUpId === item._id) ? { ...item, status: "completed" } : item)); } finally { setIsLoading(false); } }, []);
 const filteredFollowUps = useMemo(() => followUps.filter((item) => followUpFilter === "all" || (followUpFilter === "week" && isDueThisWeek(item.dueDate) && item.status !== "completed") || (followUpFilter === "overdue" && item.status === "overdue")), [followUps, followUpFilter]);
 const status = (item) => item.status === "overdue" ? t.overdue : item.status === "completed" ? t.completed : t.pending;
 return <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8"><header><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">{t.patientSupport}</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{t.followUps}</h1></header><div className="mt-5 flex flex-wrap gap-2" aria-label={t.followUps}>{[{ id: "all", label: t.all }, { id: "week", label: t.dueThisWeek }, { id: "overdue", label: t.overdue }].map((filter) => <button key={filter.id} onClick={() => setFollowUpFilter(filter.id)} className={`rounded-xl px-4 py-2.5 font-bold ${followUpFilter === filter.id ? "bg-emerald-700 text-white" : "bg-white text-slate-700 ring-1 ring-slate-200"}`}>{filter.label}</button>)}</div>{errorMessage && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{errorMessage}</p>}{isLoading ? <p className="mt-6 rounded-xl bg-white p-5">{t.loadingFollowUps}</p> : <div className="mt-6 space-y-4">{filteredFollowUps.map((item) => <Link to={"/follow-ups/" + item._id} key={item._id} className="block rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-emerald-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-emerald-700"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-bold text-slate-900">{item.patientName}</h2><p className="mt-1 text-slate-600">{item.village} · {item.visitType}</p><p className="mt-2 text-sm font-semibold text-slate-700">{t.dueDate}: {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(item.dueDate))}</p></div><span className={`w-fit rounded-full px-3 py-1 text-sm font-bold ${item.status === "overdue" ? "bg-red-100 text-red-800" : item.status === "completed" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-900"}`}>{status(item)}</span></div></Link>)}{filteredFollowUps.length === 0 && <p className="rounded-xl bg-white p-5 text-slate-600">{t.noFollowUps}</p>}</div>}</div>;
}; export default FollowUpsPage;
