import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useLanguage } from "../i18n";

const LoginPage = () => {
    const navigate = useNavigate();
    const { preferredLanguage, setPreferredLanguage, t } = useLanguage();
    const [phoneNumber, setPhoneNumber] = useState("");
    const [password, setPassword] = useState("");
    const [isLoading, setIsLoading] = useState(false);
    const [errorMessage, setErrorMessage] = useState("");
    const handleSubmit = (event) => { event.preventDefault(); setErrorMessage(""); if (!phoneNumber.trim() || !password.trim()) { setErrorMessage(t.loginError); return; } setIsLoading(true); window.setTimeout(() => { const currentUser = { _id: "mock-asha-worker", fullName: "Sunita Sharma", phoneNumber: phoneNumber.trim(), email: "sunita.asha@ashacare.demo", ashaId: "ASHA-DEMO-001", village: "Rampur", district: "Demo District", totalPoints: 15, preferredLanguage }; const authToken = "mock-auth-token"; localStorage.setItem("authToken", authToken); localStorage.setItem("currentUser", JSON.stringify(currentUser)); setIsLoading(false); navigate("/"); }, 500); };
    return <main className="grid min-h-screen place-items-center bg-gradient-to-b from-emerald-50 to-slate-50 px-4 py-8"><section className="w-full max-w-md rounded-3xl border border-emerald-100 bg-white p-6 shadow-sm sm:p-8"><div className="mb-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-700 text-2xl font-bold text-white">A</div><h1 className="mt-4 text-3xl font-bold text-slate-900">AshaCare</h1><p className="mt-2 text-slate-600">{t.loginTagline}</p></div><form onSubmit={handleSubmit} className="space-y-5">{errorMessage && <div role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{errorMessage}</div>}<label className="block font-semibold text-slate-800">{t.phoneNumber}<input type="tel" inputMode="numeric" value={phoneNumber} onChange={(event) => setPhoneNumber(event.target.value)} placeholder="9876543210" className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100" /></label><label className="block font-semibold text-slate-800">{t.password}<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder={t.enterPin} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100" /></label><fieldset><legend className="font-semibold text-slate-800">{t.language}</legend><div className="mt-2 flex gap-2">{["en", "hi"].map((language) => <button key={language} type="button" onClick={() => setPreferredLanguage(language)} aria-pressed={preferredLanguage === language} className={`rounded-lg px-4 py-2 font-semibold ${preferredLanguage === language ? "bg-emerald-700 text-white" : "bg-slate-100 text-slate-700"}`}>{language === "en" ? "English" : "हिंदी"}</button>)}</div></fieldset><button type="submit" disabled={isLoading} className="w-full rounded-xl bg-emerald-700 px-5 py-3.5 text-lg font-bold text-white hover:bg-emerald-800 disabled:opacity-60">{isLoading ? t.loggingIn : t.login}</button></form><p className="mt-5 text-center text-sm text-slate-600">{t.forgotPassword}</p><p className="mt-3 text-center text-sm"><Link to="/onboarding" className="font-semibold text-emerald-700 underline">{t.newToAshaCare}</Link></p></section></main>;
};
export default LoginPage;
