import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { mockPatients } from "../mockData/patients";
import { useLanguage } from "../i18n";

const readable = (value) => value?.replaceAll("_", " ") || "";
const PatientsPage = () => {
    const { t } = useLanguage();
    const [patients, setPatients] = useState([]);
    const [searchQuery, setSearchQuery] = useState("");
    const [isLoading, setIsLoading] = useState(true);
    const [errorMessage] = useState("");
    useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("mockPatients") || "[]"); setPatients([...mockPatients, ...saved]); } catch { setPatients(mockPatients); } finally { setIsLoading(false); } }, []);
    const filteredPatients = useMemo(() => { const query = searchQuery.trim().toLowerCase(); if (!query) return patients; return patients.filter((patient) => [patient.fullName, patient.phoneNumber, patient._id, patient.village].some((value) => value?.toLowerCase().includes(query))); }, [patients, searchQuery]);
    return <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">{t.patientSupport}</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{t.patients}</h1></div><Link to="/patients/new" className="rounded-xl bg-emerald-700 px-5 py-3 text-center font-bold text-white hover:bg-emerald-800">{t.addBeneficiary}</Link></header><label className="mt-6 block font-semibold text-slate-700">{t.searchPatients}<input value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} placeholder={t.searchPatients} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-100" /></label>{errorMessage && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{errorMessage}</p>}{isLoading ? <p className="mt-6 rounded-xl bg-white p-5 text-slate-600 shadow-sm">{t.loadingPatients}</p> : filteredPatients.length === 0 ? <section className="mt-6 rounded-2xl bg-white p-8 text-center shadow-sm"><h2 className="text-xl font-bold text-slate-900">{t.noPatients}</h2><p className="mt-2 text-slate-600">{t.noPatientsHelp}</p></section> : <div className="mt-6 grid gap-4 md:grid-cols-2">{filteredPatients.map((patient) => <Link key={patient._id} to={patient._id.startsWith("mock-patient") ? "/patients/" + patient._id : "/patients"} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-emerald-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-emerald-700"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-bold text-slate-900">{patient.fullName}</h2><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold text-emerald-800">{patient.age} {t.years}</span></div><dl className="mt-4 grid gap-3 text-slate-700"><div><dt className="text-sm text-slate-500">{t.sex}</dt><dd className="font-semibold capitalize">{patient.gender || patient.sex}</dd></div><div><dt className="text-sm text-slate-500">{t.villageWard}</dt><dd className="font-semibold">{patient.village}</dd></div>{patient.phoneNumber && <div><dt className="text-sm text-slate-500">{t.phoneNumber}</dt><dd className="font-semibold">{patient.phoneNumber}</dd></div>}<div><dt className="text-sm text-slate-500">{t.healthCategory}</dt><dd className="mt-1 flex flex-wrap gap-2">{patient.healthCategories?.map((category) => <span key={category} className="rounded-full bg-amber-50 px-2.5 py-1 text-sm font-semibold capitalize text-amber-900">{readable(category)}</span>)}</dd></div></dl></Link>)}</div>}</div>;
};
export default PatientsPage;
