import { Link, useNavigate, useParams } from "react-router-dom";
import { mockSchemes } from "../mockData/schemes";
import { useLanguage } from "../i18n";
const readableCategory = (category) => category.replaceAll("_", " ");
const SchemeDetailsPage = () => {
 const { schemeId } = useParams(); const navigate = useNavigate(); const { t } = useLanguage();
 const scheme = mockSchemes.find((item) => item._id === schemeId);
 const registration = JSON.parse(localStorage.getItem("mockSchemeRegistrations") || "[]").filter((item) => item.schemeId === schemeId).at(-1);
 if (!scheme) return <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 text-center shadow-sm"><h1 className="text-2xl font-bold text-slate-900">{t.schemeNotFound}</h1><p className="mt-2 text-slate-600">{t.schemeUnavailable}</p><Link to="/schemes" className="mt-5 inline-block rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">{t.backToSchemes}</Link></section></div>;
 return <div className="mx-auto max-w-4xl px-4 py-6 sm:px-6 lg:px-8"><button type="button" onClick={() => navigate("/schemes")} className="text-sm font-semibold text-emerald-800 underline">← {t.backToSchemes}</button><header className="mt-5"><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">{t.patientSupport}</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{scheme.schemeName}</h1><p className="mt-3 text-lg leading-7 text-slate-600">{scheme.description}</p></header><section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="grid gap-7 sm:grid-cols-2"><div><h2 className="text-lg font-bold text-slate-900">{t.benefits}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-slate-700">{scheme.benefits.map((benefit) => <li key={benefit}>{benefit}</li>)}</ul></div><div><h2 className="text-lg font-bold text-slate-900">{t.eligibility}</h2><p className="mt-3 leading-6 text-slate-700">{scheme.eligibilityText}</p></div><div><h2 className="text-lg font-bold text-slate-900">{t.requiredDocuments}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-slate-700">{scheme.requiredDocuments.map((document) => <li key={document}>{document}</li>)}</ul></div><div><h2 className="text-lg font-bold text-slate-900">{t.applicableCategories}</h2><div className="mt-3 flex flex-wrap gap-2">{scheme.applicableCategories.map((category) => <span key={category} className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold capitalize text-emerald-800">{readableCategory(category)}</span>)}</div></div></div><Link to={`/schemes/${scheme._id}/register`} className="mt-8 inline-block w-full rounded-xl bg-emerald-700 px-5 py-3.5 text-center text-lg font-bold text-white shadow-sm hover:bg-emerald-800 sm:w-auto">{registration ? t.viewRegistration : t.registerForScheme}</Link></section></div>;
};
export default SchemeDetailsPage;
